version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: trekking_miles_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trekking_miles
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trekking_miles_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: trekking_miles_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - trekking_miles_network

volumes:
  postgres_data:

networks:
  trekking_miles_network:
    driver: bridge
